on:
  release:
    types: [created]

jobs:
  release-matrix:
    name: release go binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      # fail-fast: true
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          # goversion: "https://go.dev/dl/go1.19.linux-amd64.tar.gz"
          goversion: "1.19"
          project_path: "."
          binary_name: "vocab"
